###?????? ?? -> default 8080
#server.port=8080
#
## database ?? ??
#spring.datasource.url=jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#spring.datasource.username=lhe
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
## mybatis
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=Katsu.Katsu_spring.dto
#mybatis.configuration.map-underscore-to-camel-case=true
#
##  mapper-locations: classpath:mapper/*.xml
##  config-location: classpath:mybatis-config.xml

#?????? ?? -> default 8080
server:
  port: 8080

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lhe
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml